config/routes.rb
PuntoTicketExpress::Application.routes.draw do
  get "events/:id/promotions", to: 'events#promotions', as: :promotions
  post "events/:id/promotions", to: 'promotions#create'
  get "events/:id/promotions/new", to: 'promotions#new', as: :new_promotion

  get "promotions/:id", to: 'promotions#show', as: :promotion
  put "promotions/:id/enable", to: 'promotions#enable', as: :enable_promotion
  put "promotions/:id/disable", to: 'promotions#disable', as: :disable_promotion

  get "configuration/account"
  put "configuration/update_account"
  get "configuration/producers"
  get "configuration/transactions"

  namespace :puntopagos do
    post "transactions/notification", to: 'transactions#notification'
    get "transactions/notification/:token", to: 'transactions#notification'
    get "transactions/error/:token", to: 'transactions#error', as: :transactions_error
    get "transactions/success/:token", to: 'transactions#success', as: :transactions_success
    get "transactions/new"
    post "transactions/create"
    get "transactions/:id", to: 'transactions#show', as: :transaction
    get "transactions/:id/extra_data", to: 'transactions#nested_resource', as: :transaction_nested_resource
  end

  # ROOT
  root :to => "home#index"

  # DEVISE
  devise_for :users
  ActiveAdmin.routes(self)

  # EVENTS
  get 'me/events', to: 'events#my_index'
  resources :events, only: [:show, :new, :edit, :update, :create, :destroy] do
    member do
      get :participants
      get '/statistics/sold_tickets', to: 'events#sold_tickets', as: :sold_tickets
      get :form, to: 'events#data_to_collect'
      put :publish
      put :unpublish
    end
  end

  # TICKETS
  resources :tickets, only: [:index, :show] do
    collection do
      get :download
    end
  end

  get "tickets/:id/extra_data", to: 'tickets#nested_resource', as: :ticket_nested_resource

  # PRODUCERS
  resources :producers, except: [:index]

  # CUSTOM PAGES
  get '/features', to: 'features#index'
  get '/how_works', to: 'how_works#index'
end

app/views/shared/_flash_messages.erb
<% [:notice, :error, :alert, :warning].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert alert-<%= flash_class(level) %>">
      <%= flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <p><%= t(".copyright", year: Time.now.year.to_s).html_safe %></p>
  </div>
</footer>

app/views/shared/_message.html.erb
<script type="text/ng-template" id="<%= modal_name %>.html">
  <div class="modal-header">
    <a href="javascript:void(0);" class="close" ng-click="$dismiss()">×</a>
    <h3><%= title %></h3>
  </div>
  <div class="modal-body">
    <%= message.html_safe %>
  </div>
  <div class="modal-footer">
    <button class="btn" ng-click="$dismiss()">OK</button>
  </div>
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag("punto-ticket-logo.png", :border => 0), root_path, :class => 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to t(".services"), features_path %></li>
          <li><%= link_to t(".how_works"), how_works_path %></li>
          <li><%= link_to t(".create_event"), new_event_path %></li>
          <li><%= nav_link t(".my_events"), me_events_path if user_signed_in? %></li>
        </ul>
        <ul class="nav pull-right" id="main-menu-right">
          <% if user_signed_in? %>
            <!-- dropdown menu links -->
            <div class="dropdown">
              <a class="btn dropdown-toggle" href="#">
                <%= truncate(current_user_identifier, :length => 18, :separator => ' ') %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to t(".profile"), configuration_account_path %>
                </li>
                <li>
                  <%= link_to t(".logout"), destroy_user_session_path, :method => :delete %>
                </li>
              </ul>
            </div>
            <!-- end dropdown menu links
            -->
          <% else %>
            <li>
              <%= link_to t(".sign_in"), new_user_session_path %>
            </li>
            <li>
              <span class="devider"></span>
            </li>
            <li>
              <%= link_to t(".create_account"), new_user_registration_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.haml
.sidebar
  .first-child.sidebar-header
    %i.icon-home.icon-large
    Dashboard
  .sidebar-header
    %i.icon-reorder.icon-large
    General
  %ul.nav.nav-list.sidenav.affix-top
    %li
      %a{:href => "#preview-event"}
        %i.icon-chevron-right
        Vista Previa
    %li
      %a{:href => "#edit-event"}
        %i.icon-chevron-right
        Editar Evento
  .sidebar-header
    %i.icon-share.icon-large
    Promociona
  %ul.nav.nav-list.sidenav.affix-top
    %li
      %a{:href => "#send-mails"}
        %i.icon-chevron-right
        Enviar email
    %li
      %a{:href => "#facebook-integration"}
        %i.icon-chevron-right
        Integrar Facebook
    %li
      %a{:href => "#twitter-integration"}
        %i.icon-chevron-right
        Integrar Twitter
  .sidebar-header
    %i.icon-bar-chart.icon-large
    Estadísticas
  %ul.nav.nav-list.sidenav.affix-top
    %li
      %a{:href => "#analyze-1"}
        %i.icon-chevron-right
        Estadistica 1
    %li
      %a{:href => "#analyze-2"}
        %i.icon-chevron-right
        Estadistica 2
    %li
      %a{:href => "#analyze-3"}
        %i.icon-chevron-right
        Estadistica 3
    %li
      %a{:href => "#analyze-4"}
        %i.icon-chevron-right
        Estadistica 4
    %li
      %a{:href => "#analyze-5"}
        %i.icon-chevron-right
        Estadistica 5
    %li
      %a{:href => "#analyze-6"}
        %i.icon-chevron-right
        Estadistica 6