config/routes.rb
PuntoTicketExpress::Application.routes.draw do
  get "events/:id/promotions", to: 'events#promotions', as: :promotions
  post "events/:id/promotions", to: 'promotions#create'
  get "events/:id/promotions/new", to: 'promotions#new', as: :new_promotion

  get "promotions/:id", to: 'promotions#show', as: :promotion
  put "promotions/:id/enable", to: 'promotions#enable', as: :enable_promotion
  put "promotions/:id/disable", to: 'promotions#disable', as: :disable_promotion

  get "configuration/account"
  put "configuration/update_account"
  get "configuration/producers"
  get "configuration/transactions"

  namespace :puntopagos do
    post "transactions/notification", to: 'transactions#notification'
    get "transactions/notification/:token", to: 'transactions#notification'
    get "transactions/error/:token", to: 'transactions#error', as: :transactions_error
    get "transactions/success/:token", to: 'transactions#success', as: :transactions_success
    get "transactions/new"
    post "transactions/create"
    get "transactions/:id", to: 'transactions#show', as: :transaction
    get "transactions/:id/extra_data", to: 'transactions#nested_resource', as: :transaction_nested_resource
  end

  # ROOT
  root :to => "home#index"

  # DEVISE
  devise_for :users
  ActiveAdmin.routes(self)

  # EVENTS
  get 'me/events', to: 'events#my_index'
  resources :events, only: [:show, :new, :edit, :update, :create, :destroy] do
    member do
      get :participants
      get '/statistics/sold_tickets', to: 'events#sold_tickets', as: :sold_tickets
      get :form, to: 'events#data_to_collect'
      put :publish
      put :unpublish
    end
  end

  # TICKETS
  resources :tickets, only: [:index, :show] do
    collection do
      get :download
    end
  end

  get "tickets/:id/extra_data", to: 'tickets#nested_resource', as: :ticket_nested_resource

  # PRODUCERS
  resources :producers, except: [:index]

  # CUSTOM PAGES
  get '/features', to: 'features#index'
  get '/how_works', to: 'how_works#index'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  skip_filter :authenticate_user!, only: :show
  before_filter :load_events, :only => [:my_index]

  def my_index
    params[:current_tab] = 'on_sale' if !params[:current_tab]
    @events = @events.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def participants
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html
      format.xls do
        file_path = PTE::Event::Xls.generate_participants_book(@event)
        send_file file_path, :type => "application/excel"
      end
      format.json { render json: event.users }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  def sold_tickets
    @event = Event.find(params[:id])
    render "events/statistics/sold_tickets"
  end

  # GET /events/1/edit
  def edit
  end

  def promotions
    @promotions = @event.all_promotions
  end

  def data_to_collect
    array = NestedResource.nested_attributes + @event.nested_attributes
    @attributes = (array).group_by { |h|
      h[:attr] }.map { |k, v| v.reduce(:merge) }
  end

  # POST /events
  # POST /events.json
  def create
    # creates the object and reference the current user
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_path(@event), notice: I18n.t("controller.messages.create_success") }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])

        format.html {
          if @event.is_published
            redirect_to @event, notice: I18n.t("controller.messages.update_success")

          else
            redirect_to edit_event_path, notice: I18n.t("controller.messages.update_success")
          end
        }

        format.json { head :no_content }
      else
        format.html { render action: "edit", :alert => "Something serious happened"  }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.publish
        format.html { redirect_to @event, notice: I18n.t("controller.messages.event_published") }
        format.json { head :no_content }
      else
        format.html { redirect_to @event, alert: I18n.t("controller.messages.error_publishing_event")   }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def unpublish
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.unpublish
        format.html { redirect_to @event, notice: I18n.t("controller.messages.event_unpublished") }
        format.json { head :no_content }
      else
        format.html { redirect_to @event, alert: I18n.t("controller.messages.error_unpublishing_event")   }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.disable_or_destroy

    respond_to do |format|
      format.html { redirect_to me_events_path(:current_tab => params[:current_tab]) }
      format.json { head :no_content }
    end
  end

  private
    def load_events

      case params[:current_tab]
      when 'draft' # draft events
        @events = current_user.events.draft
      when 'ended' # ended events
        @events = current_user.events.ended
      else # on sale events
        @events = current_user.events.on_sale
      end

    end
end

app/controllers/me/events_controller.rb
require 'chronic'

class Me::EventsController < ApplicationController
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    # publishing or saving
    params[:event][:is_published] = params[:publish] ? true : false

    # prepare event params
    # parsing dates and times from Javascript to Rails
    params[:event][:start_time] = Chronic.parse "#{params[:start_date]} #{params[:start_time]}"
    params[:event][:end_time] = Chronic.parse "#{params[:end_date]} #{params[:end_time]}"

    # creates the object and reference the current user
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:me, @event], notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to [:me, @event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def form_url(event)
    event.new_record? ? new_event_path : edit_event_path(id: event.id)
  end

  def disabled_class_if_new_event
  	@event.new_record? ? 'disabled' : ''
  end

  def disabled_if_published_event
     @event.is_published? ? 'disabled' : ''
  end

  def disabled_if_new_or_unpublished_event
     (@event.new_record? || !@event.is_published?) ? 'disabled' : ''
  end

  def show_or_preview_event_action(event)
    label = "buttons.preview"
    label = "buttons.show" if event.is_published?
  	link_to(t(label), event, {:class => 'action-link'})
  end

  def statistics_or_edit_event_action(event)
  	if event.is_published?
  		link_to t("buttons.statistics"), sold_tickets_event_path(event), {:class => 'action-link'}
  	else
  		link_to t("buttons.edit"), edit_event_path(event), {:class => 'action-link'}
  	end
  end

  def delete_event_action event, current_tab
    link_to t('buttons.destroy'), event_path(id: event.id, current_tab: current_tab), :class => 'action-link', method: :delete, data: { confirm: t(".delete_message") }
  end

  def publish_event_action event
    form_tag publish_event_path(event), :method => :put, :style => "margin: 0px;" do
      button_tag 'Publicar evento' ,
        class: 'btn-link action-link' ,
        :disabled => event.is_past_event? || event.is_published,
        type: :submit
    end
  end

  def tickets_limit
    @event.sell_limit || GlobalConfiguration.sell_limit
  end

  def facebook_like_button event
    url = request.original_url
    src = "//www.facebook.com/plugins/like.php?href=#{url}&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=false&amp;share=true&amp;height=35"
    content_tag(:iframe, nil, src: src, scrolling: "no", frameborder: "0", style: "border:none; overflow:hidden; height:62px; width: 600px;", allowTransparency: "true")
  end

  def event_tabs_link(tab_name, link_path, current_tab)
    current_tab = current_tab || 'on_sale'
    class_name = tab_name == current_tab ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to t(".tabs.#{tab_name}"), "#{link_path}?current_tab=#{tab_name}"
    end
  end
end

app/views/events/_form.html.erb
<%= form_for @event, :html => {name: 'form', class: 'well', novalidate: true, enctype: 'multipart/form-data'} do |f| %>
  <fieldset class="form-horizontal">
    <legend><%= t(".title") %></legend>

    <div class="control-group logo-upload">
      <%= f.label :logo, :class => 'control-label' %>
      <div class="controls logo-container">
        <%= image_tag @event.logo.url(:thumb), :class => 'small-img' %>
        <input type="file" name="event[logo]" ng-model="event.logo" />
      </div>
    </div>

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :producer %>">
      <div class="producer-hint" ng-show="{{disabled}}">
        <%= t(".no_producers_hint", new_producer_url: new_producer_path).html_safe %>
      </div>
      <select name="event[producer_id]" ng-model="event.producer"
        ng-options="p.name for p in producers track by p.id"
        ng-change="calculateAllTicketPrices()"
        class="span4" ng-disabled="{{disabled}}"
        dirty-on-blur required>
      </select>
      <div class="producer-description span5">{{event.producer.description}}</div>
    </bs:control-group>

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :name %>">
      <input type="text" name="event[name]" ng-model="event.name"
        ng-disabled="{{disabled}}" class="span4"
        dirty-on-blur required placeholder="<%= pholder(Event, :name) %>"/>
    </bs:control-group>

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :address %>">
      <input type="text" name="event[address]" ng-model="event.address"
        ng-disabled="{{disabled}}" class="span4"
        dirty-on-blur required placeholder="<%= pholder(Event, :address) %>"/>
    </bs:control-group>

    <bs:control-group bound-cg label="<%= Event.human_attribute_name :enclosure %>">
      <input type="text" name="event[enclosure]" ng-model="event.enclosure"
      ng-disabled="{{disabled}}" class="span4" placeholder="<%= pholder(Event, :enclosure) %>" />
    </bs:control-group>

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :description %>">
      <textarea name="event[description]" ng-model="event.description"
        ng-disabled="{{disabled}}" class="span4" rows="3"
        dirty-on-blur required placeholder="<%= pholder(Event, :description) %>"></textarea>
    </bs:control-group>

    <bs:control-group bound-cg label="<%= Event.human_attribute_name :custom_url %>">
      <input type="text" name="event[custom_url]" ng-model="event.customUrl"
        ng-disabled="{{disabled}}" class="span2"
        dirty-on-blur validate="url" placeholder="<%= pholder(Event, :custom_url) %>" />
      <span ng-show="event.customUrl.length > 0">{{stringToSubDomie(event.customUrl)}}</span>
    </bs:control-group>
  </fieldset>

  <fieldset class="form-horizontal">
    <input type="text" style="display: none" name="event[start_time]" ng-model="dates.startDateTime" />
    <input type="text" style="display: none" name="event[end_time]" ng-model="dates.endDateTime" />

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :start_time %>">
      <input type="text" class="input-small" validation-group="eventDates" ng-model="dates.startDate"
        data-date-format="dd/mm/yyyy" dirty-on-blur bs-datepicker model-as="startDateModel" ng-disabled="{{disabled}}"
        validate="required, date-compare: [endDateModel.$modelValue, 'LE'] as eventEndAfterStart" />
      <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>

      <pte-time-picker validation-group="eventDates" ng-disabled="{{disabled}}"
        validate="time-compare: [endTimeModel.$viewValue, startDateModel.$modelValue, endDateModel.$modelValue, 'L'] as eventEndTimeAfterStart"
        ng-model="dates.startTime" model-as="startTimeModel" dirty-on-blur/>
    </bs:control-group>

    <bs:control-group bound-cg required label="<%= Event.human_attribute_name :end_time %>">
      <input type="text" class="input-small" validation-group="eventDates" ng-model="dates.endDate"
        data-date-format="dd/mm/yyyy" dirty-on-blur bs-datepicker model-as="endDateModel" ng-disabled="{{disabled}}"
        validate="required, date-compare: [startDateModel.$modelValue, 'GE'] as eventEndAfterStart" />
      <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>

      <pte-time-picker validation-group="eventDates" ng-disabled="{{disabled}}"
        validate="time-compare: [startTimeModel.$viewValue, startDateModel.$modelValue, endDateModel.$modelValue, 'G'] as eventEndTimeAfterStart"
        ng-model="dates.endTime" model-as="endTimeModel" dirty-on-blur />
    </bs:control-group>

  </fieldset>

  <%= render :partial => "form_ticket_types" %>

  <div class="form-actions text-center">
    <input name="commit" type="submit" value="Guardar"
    class="btn btn-large btn-success btn-publish"
    ng-click="onSaveButtonClick($event)"
    ng-disabled="{{disabled}} || form.$invalid" />
  </div>
<% end %>

app/views/events/_sidebar.html.erb
<div class="sidebar">
  <div class="first-child sidebar-header">
    <i class="icon-reorder icon-large"></i>
    <%= t(".headers.info.title") %>
  </div>
  <ul class="nav nav-list sidenav affix-top">
    <li class="<%= active_if_event %>">
      <a href="<%= form_url @event %>">
        <i class="icon-chevron-right"></i>
        <%= t(".headers.info.details") %>
      </a>
    </li>
    <li class="<%= disabled_class_if_new_event %> <%= active_if_form %>">
      <a href="<%= form_event_path(id: @event.id) unless @event.new_record?  %>">
        <i class="icon-chevron-right"></i>
        <%= t(".headers.info.form") %>
      </a>
    </li>
    <li class="<%= disabled_class_if_new_event %> <%= active_if_promotion %>">
      <a href="<%= promotions_path(id: @event.id) unless @event.new_record?  %>">
        <i class="icon-chevron-right"></i>
        <%= t(".headers.info.promotions") %>
      </a>
    </li>
  </ul>
  <div class="sidebar-header">
    <i class="icon-bar-chart icon-large"></i>
    <%= t(".headers.statistic.title") %>
  </div>
  <ul class="nav nav-list sidenav affix-top">
    <li class="<%= disabled_if_new_or_unpublished_event %> <%= active_if_event_statistic %>">
      <a href="<%= sold_tickets_event_path(@event) unless @event.new_record? %>">
        <i class="icon-chevron-right"></i>
        <%= t(".headers.statistic.tickets_sold") %>
      </a>
    </li>
    <li class="<%= disabled_if_new_or_unpublished_event %> <%= active_if_participants %>">
      <a href="<%= participants_event_path unless @event.new_record? %>">
        <i class="icon-chevron-right"></i>
        <%= t(".headers.statistic.participants") %>
      </a>
    </li>
  </ul>
</div>

app/views/events/_table_my_index.html.erb
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-colored table-events">
			<thead>
				<tr>
					<th style="width: 20%;"><%= Event.human_attribute_name :name %></th>
					<th style="width: 30%;"><%= Event.human_attribute_name :address %></th>
					<th style="width: 14%;" class="border-right"><%= Event.human_attribute_name :start_time %></th>
					<th style="width: 8%;"></th>
          <th style="width: 8%;"></th>
          <% if @table_type == 'on_sale' %>
            <th style="width: 8%;"></th>
          <% end %>
          <% if @table_type == 'draft' %>
            <th style="width: 8%;"></th>
          <% end %>
          <% if @table_type != 'draft' %>
            <th style="width: 8%;"></th>
          <% end %>
					<th style="width: 8%;"></th>
				</tr>
			</thead>
			<tbody>
				<% @events.each do |event| %>
				<tr>
					<td><%= event.name %></td>
					<td><%= event.address %></td>
					<td><%= l(event.start_time, format: :short) if event.start_time %></td>
          <% if @table_type == 'on_sale' %>
            <td><%= link_to t("buttons.unpublish"), unpublish_event_path(event), {:style => "margin: 0px;", :method => :put} %><span class="pipe"></span></td>
          <% end %>
          <% if @table_type == 'draft' %>
					 <td><%= publish_event_action event %><span class="pipe"></span></td>
          <% end %>
          <td class="center"><%= show_or_preview_event_action event %><span class="pipe"></span></td>
          <td class="center"><%= delete_event_action event, @table_type %><span class="pipe"></span></td>
          <% if @table_type !=  'draft' %>
            <td class="center" style="width: 100px;"><%= link_to t("buttons.statistics"), sold_tickets_event_path(event), {:class => 'action-link'} %>
              <span class="pipe"></span>
            </td>
          <% end %>
					<td class="center"><%= link_to t("buttons.edit"), edit_event_path(event), {:class => 'action-link'} %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="text-center">
			<%= will_paginate @events %>
		</div>
	</div>
</div>

app/views/events/_unconfirmed_producer_msg.html.haml
%div{:modal => "producerModal", :close => "closeModal()"}
  .modal-header
    %h3= t(".title")
  .modal-body
    = t(".message").html_safe
  .modal-footer
    %button.btn{:type => "button", "ng-click" => "closeModal()"}
      = t("buttons.ok")

app/views/events/edit.html.erb
<div ng-controller="FormEventCtrl" ng-init='init(<%= raw @event.to_json %>, <%= raw @event.ticket_types_with_extra_data.to_json %>, <%= raw current_user.producers.to_json %>, <%= @event.is_past_event? %>, "<%= ENV["EVENT_BASE_URL"] %>")'>
  <%= render partial: 'edit_top_navbar', locals: {title: t('.title'), show_buttons: [:preview, :publish]} %>

  <div class="row" id="page_event" style="margin-top: 30px;">
  	<div class="span3">
  		<%= render 'sidebar' %>
  	</div>
  	<div class="span9">
  		<%= render 'form' %>
  	</div>
  </div>
</div>

app/views/events/new.html.erb
<div class="page-header">
	<h1><%= t(".title") %></h1>
</div>

<div class="row" id="page_event" ng-controller="FormEventCtrl" ng-init='init(<%= raw @event.to_json %>, <%= raw @event.ticket_types_with_extra_data.to_json %>, <%= raw current_user.producers.to_json %>, <%= @event.is_past_event? %>, "<%= ENV["EVENT_BASE_URL"] %>")'>
	<div class="span3">
		<%= render 'sidebar' %>
	</div>
	<div class="span9">
		<%= render 'form' %>
	</div>
</div>

app/views/events/participants.html.erb
<div class="page-header">
	<h1>
		<%= t(".title") %>
	</h1>
</div>
<div class="row">
	<div class="span3">
		<%= render 'sidebar' %>
	</div>
	<div class="span9">
		<div class="well">
			<legend>
				<%= t(".subtitle", event_name: @event.name) %>
			</legend>
			<% if @event.participants_table_header.size.zero? %>
				<%= t(".no_data_message") %>
			<% else %>
				<table class="table table-condensed table-bordered pte-table">
					<thead>
						<tr>
							<% @event.participants_table_header.each do |col| %>
								<th>
									<%= NestedResource.human_attribute_name col %>
								</th>
							<% end %>
							<th></th>
						</tr>
					</thead>
					<tbody>
            <% participants = @event.participants %>
						<% participants.each do |data| %>
							<tr>
								<% data.each do |attr| %>
									<% unless attr == data.last %>
										<td>
											<%= attr %>
										</td>
									<% end %>
								<% end %>
								<td>
									<%= link_to t('buttons.show'), data.last %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
				<%= will_paginate participants %>
				<div class="form-actions">
					<%= link_to t("buttons.download"), participants_event_path(@event, format: :xls), :class => 'btn btn-success btn-large' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/events/promotions.html.erb
<div ng-controller="EventPromotionsCtrl" ng-init='init(<%= raw @event.producer.to_json %>, <%= @event.is_past_event? %>)'>
  <%= render partial: 'events/edit_top_navbar', locals: {title: t('.title'), show_buttons: [:preview, :publish]} %>

  <div class="row-fluid" style="margin-top: 30px;">
    <div class="span3">
      <%= render 'events/sidebar' %>
    </div>
    <div class="span9">
      <div class="well">
        <legend>
          <%= t(".promo_title", event_name: @event.name) %>
        </legend>
        <table class="table table-condensed table-bordered pte-table">
          <thead>
            <tr>
              <th><%= Promotion.human_attribute_name :name %></th>
              <th class="center"><%= Promotion.human_attribute_name :promotion_type %></th>
              <th class="center"><%= Promotion.human_attribute_name :available %></th>
              <th class="center"></th>
            </tr>
            <tbody></tbody>
            <% @promotions.each do |promo| %>
              <tr>
                <td class="<%= line_through(promo.enabled) %>">
                  <%= link_to promo.name, promotion_path(promo) %>
                </td>
                <td class="<%= line_through(promo.enabled) %>">
                  <%= short_promo_type(promo) %>
                </td>
                <td class="center">
                  <%= human_boolean(promo.is_promo_available?) %>
                </td>
                <td>
                  <%= enable_promo_link(promo) %>
                </td>
              </tr>
            <% end %>
          </thead>
        </table>
        <div class="form-actions">
          <%= link_to t("buttons.new_promotion"), new_promotion_path(@event), :class => 'btn btn-success btn-large' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div ng-controller="EventShowCtrl" ng-init='init(<%= raw @event.ticket_types_for_table.to_json %>, <%= !@event.is_published %>, <%= @event.is_past_event? %>, <%= @event.in_publish_range? %>, <%= tickets_limit %>, <%= raw PTE::Theme::types_to_a.to_json %>, "<%= @event.theme %>")'>
  <!-- load theme -->
  <!-- if there is no associated theme, load the default css -->
  <%= stylesheet_link_tag "themes/#{@event.theme || PTE::Theme::default}", :id => 'theme_css' %>

  <%= render "show_top_navbar" unless(@event.is_published) %>

  <div class="page-header">
  	<div class="row-fluid">
  		<div class="span8">
  			<h1><%= @event.name %></h1>
  			<p><%= @event.description %></p>
  		</div>
  		<div class="span4">
  			<%= image_tag @event.logo.url(:medium), :class => 'pull-right medium-img' if @event.logo.file? %>
  		</div>
  	</div>
  </div>

  <div class="row" id="page_event">
  	<div class="span4">
  		<div class="panel">
  			<div class="panel-heading panel-title">
  				<i class="icon-bullhorn"></i>
  				<%= t(".titles.producer") %>
  			</div>
  			<h5><%= @event.producer_name %></h5>
  			<p><%= @event.producer_description %></p>
  		</div>
  		<div class="panel">
  			<div class="panel-heading panel-title">
  				<i class="icon-map-marker"></i>
  				<%= t(".titles.when") %>
  			</div>
        <p><%= l(@event.start_time, format: :pte) if @event.start_time %></p>
  		</div>
      <div class="panel">
        <div class="panel-heading panel-title">
          <i class="icon-map-marker"></i>
          <%= t(".titles.where") %>
        </div>
        <p><%= @event.address %></p>
        <p><%= @event.enclosure if @event.enclosure %></p>
      </div>
  	</div>
  	<div class="span8">
  		<%= render :partial => "shared/message", :locals => { :message => t(".not_tickets_msg.message"), :title => t(".not_tickets_msg.title"), :modal_name => "notTicketsModal"} %>

  		<%= render :partial => "shared/message", :locals => { :message => t(".prevent_buy_msg.message"), :title => t(".prevent_buy_msg.title"), :modal_name => "buyModal"} %>

      <%= render :partial => "shared/message", :locals => { :message => t(".limit_exceeded_msg.message", qty: tickets_limit), :title => t(".limit_exceeded_msg.title"), :modal_name => "limitModal"} %>

      <%= render :partial => "shared/message", :locals => { :message => t(".old_event_msg.message", qty: tickets_limit), :title => t(".old_event_msg.title"), :modal_name => "oldEventModal"} %>

      <%= render :partial => "shared/message", :locals => { :message => t(".publish_range_msg.message"), :title => t(".publish_range_msg.title"), :modal_name => "publishRangeModal"} %>

  		<%= form_tag puntopagos_transactions_new_path, :method => :get,
  		"ng-submit" => "validateTicketTypes($event)" do |f| %>
  		<div class="panel panel-primary">
  			<div class="panel-heading panel-title">
  				<i class="icon-ticket"></i>
  				<%= t(".titles.tickets") %>
  			</div>
  			<table class="table table-striped table-colored">
  				<thead>
  					<tr>
  						<th><%= TicketType.human_attribute_name(:name) %></th>
  						<th><%= TicketType.human_attribute_name(:price) %></th>
  						<th ng-show="anyPromo"><%= TicketType.human_attribute_name(:discount) %></th>
  						<th><%= TicketType.human_attribute_name(:bought_quantity) %></th>
  					</tr>
  				</thead>
  				<tbody>
  					<tr ng-repeat="t in ticketTypes">
  						<td class="stock-empty">
                <div ng-class="{'line-through':stockEmpty(t)}" class="type-label">{{t.name}}</div>
                <div ng-show="stockEmpty(t)" class="empty-label"><%= t(".empty_stock_message") %></div>
              </td>
  						<td ng-class="{'line-through':typeWithPromo(t) || stockEmpty(t) }">
  							{{t.price | pteCurrency}}
  						</td>
  						<td ng-show="anyPromo">
  							<div ng-show="typeWithPromo(t)">
  								{{t.promotion_price | pteCurrency}}
  							</div>
  						</td>
  						<td>
  							<select class="input-small" ng-model="t.bought_quantity" ng-disabled="stockEmpty(t)">
  							<%= options_for_select((0..tickets_limit).step(1), 0) %>
  							</select>
  						</td>
  					</tr>
  				</tbody>
  			</table>
  			<legend></legend>

  			<input type="hidden" name="ticket_types[{{type.id}}][bought_quantity]" value="{{type.bought_quantity}}" ng-repeat="type in ticketTypes"/>

  			<div class="text-center">
  				<input type="submit" value="<%= t("buttons.buy_now") %>"
  				class="btn btn-success btn-primary buy-btn"/>
  			</div>
  		</div>
  		<% end %>
      <%= facebook_like_button @event %>
  	</div>
  </div>
</div>