config/routes.rb
PuntoTicketExpress::Application.routes.draw do
  get "events/:id/promotions", to: 'events#promotions', as: :promotions
  post "events/:id/promotions", to: 'promotions#create'
  get "events/:id/promotions/new", to: 'promotions#new', as: :new_promotion

  get "promotions/:id", to: 'promotions#show', as: :promotion
  put "promotions/:id/enable", to: 'promotions#enable', as: :enable_promotion
  put "promotions/:id/disable", to: 'promotions#disable', as: :disable_promotion

  get "configuration/account"
  put "configuration/update_account"
  get "configuration/producers"
  get "configuration/transactions"

  namespace :puntopagos do
    post "transactions/notification", to: 'transactions#notification'
    get "transactions/notification/:token", to: 'transactions#notification'
    get "transactions/error/:token", to: 'transactions#error', as: :transactions_error
    get "transactions/success/:token", to: 'transactions#success', as: :transactions_success
    get "transactions/new"
    post "transactions/create"
    get "transactions/:id", to: 'transactions#show', as: :transaction
    get "transactions/:id/extra_data", to: 'transactions#nested_resource', as: :transaction_nested_resource
  end

  # ROOT
  root :to => "home#index"

  # DEVISE
  devise_for :users
  ActiveAdmin.routes(self)

  # EVENTS
  get 'me/events', to: 'events#my_index'
  resources :events, only: [:show, :new, :edit, :update, :create, :destroy] do
    member do
      get :participants
      get '/statistics/sold_tickets', to: 'events#sold_tickets', as: :sold_tickets
      get :form, to: 'events#data_to_collect'
      put :publish
      put :unpublish
    end
  end

  # TICKETS
  resources :tickets, only: [:index, :show] do
    collection do
      get :download
    end
  end

  get "tickets/:id/extra_data", to: 'tickets#nested_resource', as: :ticket_nested_resource

  # PRODUCERS
  resources :producers, except: [:index]

  # CUSTOM PAGES
  get '/features', to: 'features#index'
  get '/how_works', to: 'how_works#index'
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
  def account
    authorize! :config, :account
    @user = current_user
  end

  def update_account
    authorize! :config, :account
    @user = current_user

    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to configuration_account_path, notice: t("configuration.account.successfully_updated_message") }
        format.json { head :no_content }
      else
        format.html { render action: "account" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def producers
    authorize! :config, :producers
    @producers = current_user.producers
  end

  def transactions
    authorize! :config, :transactions
    @transactions = current_user.completed_transactions.order("transaction_time desc")
  end
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/views/configuration/_sidebar.html.erb
<div class="sidebar">
  <div class="first-child sidebar-header">
    <i class="icon-cog icon-large"></i>
    <%= t("configuration.title") %>
  </div>
  <ul class="nav nav-list sidenav affix-top">
    <li class="<%= active_if_account %>">
      <a href="<%= configuration_account_path %>">
        <i class="icon-chevron-right"></i>
        <%= t("configuration.account.title") %>
      </a>
    </li>
    <li class="<%= active_if_transaction %>">
      <a href="<%= configuration_transactions_path %>">
        <i class="icon-chevron-right"></i>
        <%= t("configuration.transactions.title") %>
      </a>
    </li>
    <li class="<%= active_if_producer %>">
      <a href="<%= configuration_producers_path %>">
        <i class="icon-chevron-right"></i>
        <%= t("configuration.producers.title") %>
      </a>
    </li>
  </ul>
</div>

app/views/configuration/account.html.erb
<div class="page-header">
  <h1>
    <%= t(".title") %>
  </h1>
</div>
<div class="row" id="page_account">
  <div class="span3">
    <%= render 'sidebar' %>
  </div>
  <div class="span9">
    <div class="well">
      <legend>
        <%= t(".subtitle") %>
      </legend>
      <%= form_for(@user, :url => configuration_update_account_path, :html => { :method => :put, :class => 'form-horizontal' }) do |f| %>
        <%= control_group f, :email, f.text_field(:email, :class => 'span4') %>
        <%= control_group f, :name, f.text_field(:name, :class => 'span4') %>
        <%= control_group f, :password, f.password_field(:password, :autocomplete => 'off', :class => 'span4'), {ignore_required: true} %>
        <%= control_group f, :password_confirmation, f.password_field(:password_confirmation, :autocomplete => 'off', :class => 'span4') %>
        <div class="form-actions">
          <%= f.submit t('buttons.save'), :class => 'btn btn-success btn-large' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/configuration/producers.html.erb
<div class="page-header">
  <h1><%= t(".title") %></h1>
</div>
<div class="row" id="page_account">
  <div class="span3">
    <%= render 'sidebar' %>
  </div>
  <div class="span9">
    <div class="well">
      <legend>
        <%= t(".subtitle") %>
      </legend>
      <table class="table table-condensed table-bordered pte-table">
        <thead>
          <tr>
            <th><%= Producer.human_attribute_name :name %></th>
            <th><%= Producer.human_attribute_name :contact_name %></th>
            <th><%= Producer.human_attribute_name :phone %></th>
            <th><%= Producer.human_attribute_name :confirmed %></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @producers.each do |producer| %>
          <tr>
            <td><%= producer.name %></td>
            <td><%= producer.contact_name %></td>
            <td><%= producer.phone %></td>
            <td class="center"><%= human_boolean(producer.confirmed) %></td>
            <td><%= link_to t('buttons.show'), producer_path(producer) %></td>
            <td><%= link_to t('buttons.edit'), edit_producer_path(producer) %></td>
            <td><%= link_to t('buttons.destroy'), producer_path(producer), method: :delete %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="form-actions">
        <%= link_to t(".new_producer_btn"), new_producer_path, :class => 'btn btn-success btn-large' %>
      </div>
    </div>
  </div>
</div>

app/views/configuration/transactions.html.erb
<div class="page-header">
  <h1><%= t(".title") %></h1>
</div>
<div class="row" id="page_account">
  <div class="span3">
    <%= render 'sidebar' %>
  </div>
  <div class="span9">
    <div class="well">
      <legend>
        <%= t(".subtitle") %>
      </legend>
      <table class="table table-condensed table-bordered pte-table">
        <thead>
          <tr>
            <th><%= Transaction.human_attribute_name :transaction_time %></th>
            <th><%= Transaction.human_attribute_name :event %></th>
            <th><%= Transaction.human_attribute_name :tickets_count %></th>
            <th><%= Transaction.human_attribute_name :amount %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @transactions.each do |transaction| %>
            <tr>
              <td><%= l(transaction.transaction_time, format: :short) %></td>
              <td><%= transaction.event_name %></td>
              <td><%= transaction.tickets_quantity %></td>
              <td><%= number_to_currency(transaction.total_amount) %></td>
              <td><%= link_to t('buttons.show'), puntopagos_transaction_path(transaction) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>