config/routes.rb
PuntoTicketExpress::Application.routes.draw do
  get "events/:id/promotions", to: 'events#promotions', as: :promotions
  post "events/:id/promotions", to: 'promotions#create'
  get "events/:id/promotions/new", to: 'promotions#new', as: :new_promotion

  get "promotions/:id", to: 'promotions#show', as: :promotion
  put "promotions/:id/enable", to: 'promotions#enable', as: :enable_promotion
  put "promotions/:id/disable", to: 'promotions#disable', as: :disable_promotion

  get "configuration/account"
  put "configuration/update_account"
  get "configuration/producers"
  get "configuration/transactions"

  namespace :puntopagos do
    post "transactions/notification", to: 'transactions#notification'
    get "transactions/notification/:token", to: 'transactions#notification'
    get "transactions/error/:token", to: 'transactions#error', as: :transactions_error
    get "transactions/success/:token", to: 'transactions#success', as: :transactions_success
    get "transactions/new"
    post "transactions/create"
    get "transactions/:id", to: 'transactions#show', as: :transaction
    get "transactions/:id/extra_data", to: 'transactions#nested_resource', as: :transaction_nested_resource
  end

  # ROOT
  root :to => "home#index"

  # DEVISE
  devise_for :users
  ActiveAdmin.routes(self)

  # EVENTS
  get 'me/events', to: 'events#my_index'
  resources :events, only: [:show, :new, :edit, :update, :create, :destroy] do
    member do
      get :participants
      get '/statistics/sold_tickets', to: 'events#sold_tickets', as: :sold_tickets
      get :form, to: 'events#data_to_collect'
      put :publish
      put :unpublish
    end
  end

  # TICKETS
  resources :tickets, only: [:index, :show] do
    collection do
      get :download
    end
  end

  get "tickets/:id/extra_data", to: 'tickets#nested_resource', as: :ticket_nested_resource

  # PRODUCERS
  resources :producers, except: [:index]

  # CUSTOM PAGES
  get '/features', to: 'features#index'
  get '/how_works', to: 'how_works#index'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  skip_filter :authenticate_user!, only: :show
  before_filter :load_events, :only => [:my_index]

  def my_index
    params[:current_tab] = 'on_sale' if !params[:current_tab]
    @events = @events.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def participants
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html
      format.xls do
        file_path = PTE::Event::Xls.generate_participants_book(@event)
        send_file file_path, :type => "application/excel"
      end
      format.json { render json: event.users }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  def sold_tickets
    @event = Event.find(params[:id])
    render "events/statistics/sold_tickets"
  end

  # GET /events/1/edit
  def edit
  end

  def promotions
    @promotions = @event.all_promotions
  end

  def data_to_collect
    array = NestedResource.nested_attributes + @event.nested_attributes
    @attributes = (array).group_by { |h|
      h[:attr] }.map { |k, v| v.reduce(:merge) }
  end

  # POST /events
  # POST /events.json
  def create
    # creates the object and reference the current user
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_path(@event), notice: I18n.t("controller.messages.create_success") }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])

        format.html {
          if @event.is_published
            redirect_to @event, notice: I18n.t("controller.messages.update_success")

          else
            redirect_to edit_event_path, notice: I18n.t("controller.messages.update_success")
          end
        }

        format.json { head :no_content }
      else
        format.html { render action: "edit", :alert => "Something serious happened"  }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def publish
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.publish
        format.html { redirect_to @event, notice: I18n.t("controller.messages.event_published") }
        format.json { head :no_content }
      else
        format.html { redirect_to @event, alert: I18n.t("controller.messages.error_publishing_event")   }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def unpublish
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.unpublish
        format.html { redirect_to @event, notice: I18n.t("controller.messages.event_unpublished") }
        format.json { head :no_content }
      else
        format.html { redirect_to @event, alert: I18n.t("controller.messages.error_unpublishing_event")   }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.disable_or_destroy

    respond_to do |format|
      format.html { redirect_to me_events_path(:current_tab => params[:current_tab]) }
      format.json { head :no_content }
    end
  end

  private
    def load_events

      case params[:current_tab]
      when 'draft' # draft events
        @events = current_user.events.draft
      when 'ended' # ended events
        @events = current_user.events.ended
      else # on sale events
        @events = current_user.events.on_sale
      end

    end
end

app/controllers/me/events_controller.rb
require 'chronic'

class Me::EventsController < ApplicationController
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    # publishing or saving
    params[:event][:is_published] = params[:publish] ? true : false

    # prepare event params
    # parsing dates and times from Javascript to Rails
    params[:event][:start_time] = Chronic.parse "#{params[:start_date]} #{params[:start_time]}"
    params[:event][:end_time] = Chronic.parse "#{params[:end_date]} #{params[:end_time]}"

    # creates the object and reference the current user
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:me, @event], notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to [:me, @event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def form_url(event)
    event.new_record? ? new_event_path : edit_event_path(id: event.id)
  end

  def disabled_class_if_new_event
  	@event.new_record? ? 'disabled' : ''
  end

  def disabled_if_published_event
     @event.is_published? ? 'disabled' : ''
  end

  def disabled_if_new_or_unpublished_event
     (@event.new_record? || !@event.is_published?) ? 'disabled' : ''
  end

  def show_or_preview_event_action(event)
    label = "buttons.preview"
    label = "buttons.show" if event.is_published?
  	link_to(t(label), event, {:class => 'action-link'})
  end

  def statistics_or_edit_event_action(event)
  	if event.is_published?
  		link_to t("buttons.statistics"), sold_tickets_event_path(event), {:class => 'action-link'}
  	else
  		link_to t("buttons.edit"), edit_event_path(event), {:class => 'action-link'}
  	end
  end

  def delete_event_action event, current_tab
    link_to t('buttons.destroy'), event_path(id: event.id, current_tab: current_tab), :class => 'action-link', method: :delete, data: { confirm: t(".delete_message") }
  end

  def publish_event_action event
    form_tag publish_event_path(event), :method => :put, :style => "margin: 0px;" do
      button_tag 'Publicar evento' ,
        class: 'btn-link action-link' ,
        :disabled => event.is_past_event? || event.is_published,
        type: :submit
    end
  end

  def tickets_limit
    @event.sell_limit || GlobalConfiguration.sell_limit
  end

  def facebook_like_button event
    url = request.original_url
    src = "//www.facebook.com/plugins/like.php?href=#{url}&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=false&amp;share=true&amp;height=35"
    content_tag(:iframe, nil, src: src, scrolling: "no", frameborder: "0", style: "border:none; overflow:hidden; height:62px; width: 600px;", allowTransparency: "true")
  end

  def event_tabs_link(tab_name, link_path, current_tab)
    current_tab = current_tab || 'on_sale'
    class_name = tab_name == current_tab ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to t(".tabs.#{tab_name}"), "#{link_path}?current_tab=#{tab_name}"
    end
  end
end

app/views/me/events/_form.html.erb
<%= form_for [:me, @event], html: {name: 'form', class: 'well', novalidate: true} do |f| %>
  <fieldset class="form-horizontal">
    <legend>Detalles del Evento</legend>
    <% if @event.errors.any? %>
      <div id="error_explanation" class="alert alert-error">
        <h4 class="alert-heading"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>
        <br />
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name,
          :class => 'input-xlarge',
          'ng-model' => 'events.name',
          'ng-minlength' => '3',
          'form-validate' => '',
          'required' => ''
        %>
        <!-- validation -->
        <div ng-show="(form['event[name]'].$dirty && form['event[name]'].$invalid)" class="input-error">
          <label ng-show="form['event[name]'].$error.required">
            El nombre del evento no puede estar en blanco
          </label>
          <label ng-show="form['event[name]'].$error.minlength">
            El nombre del evento debe tener al menos 3 caracteres
          </label>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address,
          :class => 'input-xlarge',
          'ng-model' => 'events.address',
          'ng-minlength' => '3',
          'form-validate' => '',
          'required' => ''
        %>
        <!-- validation -->
        <div ng-show="(form['event[address]'].$dirty && form['event[address]'].$invalid)" class="input-error">
          <label ng-show="form['event[address]'].$error.required">
            La dirección del evento no puede estar en blanco
          </label>
          <label ng-show="form['event[address]'].$error.minlength">
            La dirección del evento debe tener al menos 3 caracteres
          </label>
        </div>

      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :rows => '3', :class => 'input-xlarge' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :organizer_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :organizer_name,
        :class => 'input-xlarge',
          'ng-model' => 'events.organizer_name',
          'ng-minlength' => '3',
          'form-validate' => '',
          'required' => ''
        %>
        <!-- validation -->
        <div ng-show="(form['event[organizer_name]'].$dirty && form['event[organizer_name]'].$invalid)" class="input-error">
          <label ng-show="form['event[organizer_name]'].$error.required">
            El nombre del organizador del evento no puede estar en blanco
          </label>
          <label ng-show="form['event[organizer_name]'].$error.minlength">
            El nombre del organizador del evento debe tener al menos 3 caracteres
          </label>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :organizer_description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :organizer_description, :rows => '3', :class => 'input-xlarge' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :custom_url, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :custom_url, :class => 'input-xlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label 'Fecha y Horario', :class => 'control-label' %>
      <div class="controls">

        <div class="input-append">
          <input name="start_date"
            class="input-small"
            type="text"
            ng-model="time.dates.startDate"
            data-date-format="dd/mm/yyyy"
            data-model-ref="time"
            form-validate bs-datepicker required />
          <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>
        </div>

        <div class="input-append">
          <input name="start_time" class="input-mini" type="text" ng-model="time.times.startTime" bs-timepicker>
          <button type="button" class="btn" data-toggle="timepicker"><i class="icon-time"></i></button>
        </div>
        -
        <div class="input-append">
          <input name="end_date" class="input-small" type="text" ng-model="time.dates.endDate" data-date-format="dd/mm/yyyy" bs-datepicker>
          <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>
        </div>
        <div class="input-append">
          <input name="end_time" class="input-mini" type="text" ng-model="time.times.endTime" bs-timepicker>
          <button type="button" class="btn" data-toggle="timepicker"><i class="icon-time"></i></button>
        </div>

        <!-- you must define a filter to accept more than one validation -->
        <!-- custom validation -->
        <div ng-show="form.start_date.$dirty && form.start_date.$invalid" class="input-error">
          <label ng-show="form.start_date.$error.required">
            La fecha de inicio no puede estar en blanco
          </label>
          <label ng-show="form.start_date.$error.date">
            El formto de fecha es incorrecto
          </label>
        </div>
        <!-- custom validation -->
        <form-validate name="timesStart" ng-model="time" validate-type="starttime" required>
        <form-validate name="timesEnd" ng-model="time" validate-type="startgreaterend" required>
        <div class="row-fluid">
          <div ng-show="form.timesStart.$error.starttime" class="input-error span6 no-space">
            <label>
              El comienzo del evento no puede ser menor que la fecha actual
            </label>
          </div>
          <div ng-show="form.timesEnd.$error.startgreaterend" class="input-error span6 no-space">
            <label>
              El comienzo del evento no puede ser mayor que el final
            </label>
          </div>
        </div>

      </div>


    </div>

  </fieldset>

  <fieldset>
    <legend>Crea los Tickets</legend>
    <!-- custom validation -->
    <form-validate name="events" ng-model="tickets" validate-type="minrepeat" required>
    <div ng-show="form.events.$error.minrepeat" class="alert alert-error">
      <span>Debe crear al menos un tipo de ticket para guardar o publicar este evento.</span>
    </div>

    <div class="control-group text-center">
      <button ng-click="addTicket()" type="button" class="btn btn-success">Agrega un ticket</button>
    </div>
    <br />
    <table class="table table-bordered" ng-show="tickets.length" ng-animate="{show: 'event-show', hide: 'event-hide'}">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Precio</th>
          <th>Cantidad</th>
          <th></th>
        </th>
        </tr>
      </thead>
      <tbody>
        <tr ng-repeat="ticket in tickets">
          <!-- do not use only ng-for because not only need a dynamic name for validations,
          also need a specific structure for rails -->
            <td>
              <ng-form name="formInName">
                <input class="input-xlarge"
                type="text"
                ng-model="ticket.name"
                name="event[ticket_types_attributes][{{$index}}][name]"
                form-validate required>
                <!-- validation -->
                <div ng-show="formInName['event[ticket_types_attributes][\{\{$index}\}\][name]'].$dirty && formInName['event[ticket_types_attributes][\{\{$index}\}\][name]'].$invalid" class="input-error">
                  <label ng-show="formInName['event[ticket_types_attributes][\{\{$index}\}\][name]'].$error.required">
                    El nombre del ticket no puede estar en blanco
                  </label>
                </div>
              </ng-form>
            </td>
            <td>
              <ng-form name="formInPrice">
                <input class="input-small"
                type="text"
                ng-model="ticket.price"
                name="event[ticket_types_attributes][{{$index}}][price]"
                form-validate required>
                <!-- validation -->
                <div ng-show="formInPrice['event[ticket_types_attributes][\{\{$index}\}\][price]'].$dirty && formInPrice['event[ticket_types_attributes][\{\{$index}\}\][price]'].$invalid" class="input-error">
                  <label ng-show="formInPrice['event[ticket_types_attributes][\{\{$index}\}\][price]'].$error.required">
                    El precio del ticket no puede estar en blanco
                  </label>
                </div>
              </ng-form>
            </td>
            <td>
              <ng-form name="formInQuantity">
                <input class="input-small"
                type="number"
                ng-model="ticket.qty"
                name="event[ticket_types_attributes][{{$index}}][quantity]"
                form-validate required>
                <!-- validation -->
                <div ng-show="formInQuantity['event[ticket_types_attributes][\{\{$index}\}\][quantity]'].$dirty && formInQuantity['event[ticket_types_attributes][\{\{$index}\}\][quantity]'].$invalid" class="input-error">
                  <label ng-show="formInQuantity['event[ticket_types_attributes][\{\{$index}\}\][quantity]'].$error.required">
                    La cantidad de tickets no puede estar en blanco
                  </label>
                  <label ng-show="formInQuantity['event[ticket_types_attributes][\{\{$index}\}\][quantity]'].$error.number">
                    Formato no valido
                  </label>
                </div>
              </ng-form>
              </td>
            <td><a class="close" ng-click="deleteTicket($index)">×</a></td>
        </tr>
      </tbody>
    </table>
  </fieldset>

  <div class="form-actions">
    <%= f.submit 'Publicar evento', :name => 'publish', :class => 'btn btn-success btn-primary btn-large'  %>
    <input class="btn btn-large" name="commit" type="submit" value="Guardar evento" ng-show="form.$valid">
    <input value="Guardar evento" type="button" class="btn btn-large" ng-click="allowValidation()" ng-show="form.$invalid">
  </div>

<% end %>

app/views/me/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<% if can? :read, @event %>
  <%= link_to 'Show', @event %> |
<% end %>
<%= link_to 'Back', me_events_path %>

app/views/me/events/index.html.erb
<% if notice %>
  <div id="notice" class="alert alert-success"><%= notice %></div>
<% end %>

<div class="page-header">
  <h1>Tus Eventos</h1>
</div>

<table class="table table-striped">
  <tr>
    <th><%=t 'activerecord.attributes.event.name' %></th>
    <th><%=t 'activerecord.attributes.event.address' %></th>
    <th><%=t 'activerecord.attributes.event.description' %></th>
    <th><%=t 'activerecord.attributes.event.start_time' %></th>
    <th><%=t 'activerecord.attributes.event.is_published' %></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.address %></td>
    <td><%= event.description %></td>
    <td><%= l event.start_time, format: :short %></td>
    <td><%= boolean_to_words(event.is_published) %></td>
    <td><%= link_to 'Ver', [:me, event], :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Editar', edit_me_event_path(event), :class => 'btn btn-mini' %></td>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, Event %>
  <%= link_to 'Crear Evento', new_me_event_path, :class => 'btn btn-success' %>
<% end %>

app/views/me/events/new.html.erb
<div class="page-header">
  <h1>Crear un Evento</h1>
</div>

<!-- angular controller -->
<div id="page_event" class="row" ng-controller="EventCtrl">
  <div class="span10 offset1">
    <%= render 'form' %>
    <%= link_to 'Back', me_events_path %>
  </div>
</div>

app/views/me/events/show.html.erb
<div class="page-header">
  <h1>Estadisticas</h1>
</div>